#!/bin/bash

spath="$(dirname "$(readlink -f "$0")")"
source $spath/utils/support
source $spath/utils/banners

ARCH=$1
DISTRO=$2
TDIR=$3
OUT_TMP=$4
PACKAGES=$5
EXTRA_FILES="$(cat $6)"
INSTALL_BCC=$7
SKIP_DEVICE=$8		# Skip any device-specific stages
MIRROR="${9:-http://deb.debian.org/debian}"
VARIANT="--variant=minbase"

# qemu-debootstrap was deprecated and removed from debootstrap. Modern
# debootstrap performs the foreign-arch bootstrap transparently as long as
# qemu-user-static is installed and its binfmt handlers are registered.
time debootstrap --arch $ARCH --include=$PACKAGES $VARIANT \
	$DISTRO $OUT_TMP $MIRROR

# Some reason debootstrap leaves these mounted
umount $OUT_TMP/proc/sys/fs/binfmt_misc || true
umount $OUT_TMP/proc || true

# Make bash the default shell
chroot $OUT_TMP rm /bin/sh || true
chroot $OUT_TMP ln -s /bin/bash /bin/sh || true
cp $spath/addons/bashrc $OUT_TMP/.bashrc
cp $spath/addons/bashrc.common $OUT_TMP/.bashrc.common
cp $spath/addons/bashrc.silent $OUT_TMP/.bashrc.silent
cp $spath/addons/get_kvers.sh $OUT_TMP/

for f in $EXTRA_FILES; do
	if [ $f == "none" ]; then continue; fi
	cp $f $OUT_TMP/
done

# Cleanup
rm -rf $OUT_TMP/lib/udev/*
rm -rf $OUT_TMP/var/lib/apt/lists/*
rm -rf $OUT_TMP/var/cache/apt/archives/*deb
rm -rf $OUT_TMP/usr/share/locale/*
rm -rf $OUT_TMP/usr/lib/share/locale/*
rm -rf $OUT_TMP/usr/share/doc/*
rm -rf $OUT_TMP/usr/lib/share/doc/*
rm -rf $OUT_TMP/usr/share/ieee-data/*
rm -rf $OUT_TMP/usr/lib/share/ieee-data/*
rm -rf $OUT_TMP/usr/share/man/*
rm -rf $OUT_TMP/usr/lib/share/man/*

# Fix apt-get issue: Android requires the _apt user's group to be the
# AID_INET group (gid 3003) which is android specific, otherwise apt-get
# cannot access the network on device. The _apt uid is not stable across
# Debian releases (e.g. 100 on buster, 42 on bookworm), so match on the
# username and only rewrite the primary gid (65534/nogroup -> 3003).
if grep -q '^_apt:' $OUT_TMP/etc/passwd; then
	sed -i -E 's/^(_apt:x:[0-9]+):[0-9]+:/\1:3003:/' $OUT_TMP/etc/passwd
else
	c_warning "_apt user not found, skipping AID_INET group fix"
fi

# Add a default DNS server
echo "nameserver 4.2.2.2" > $OUT_TMP/etc/resolv.conf

# Clone BCC if needed
if [ $INSTALL_BCC -eq 1 ]; then
	# Modern BCC vendors libbpf/blazesym/bpftool as git submodules, so they
	# must be fetched up front (--recurse-submodules) or the build fails with
	# a missing libbpf/src/bpf.h. Fetch them here on the host so the in-chroot
	# build does not need to touch git at all.
	git clone --recurse-submodules https://github.com/iovisor/bcc.git $TDIR/debian/bcc-master
	cp $spath/bcc/build-bcc.sh $TDIR/debian/bcc-master/
	chroot $OUT_TMP /bcc-master/build-bcc.sh || die 11 "BCC build failed"
fi

# Should we really do this?
chmod -R 0777 $TDIR/

[ $SKIP_DEVICE -eq 0 ] || exit 0

c_info "Compressing new filesystem to prepare to push to Android /data/androdeb/"
tar -zcf $TDIR/deb.tar.gz -C $TDIR debian

chmod 0777 $TDIR/deb.tar.gz
